# Generated by Django 5.2 on 2025-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message_type', models.CharField(max_length=20)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
