# Generated by Django 5.2 on 2025-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
